### ISSUE TITLE
Log flooding "[Tapo] Failed to check for updates, delaying 500ms"

### ISSUE THREAD

**Issue by EnderSurge** [RaresAil/homebridge-tplink-smart-light#101]
### Describe The Bug

My homebridge log is flooded with "[Tapo] Failed to check for updates, delaying 500ms" along with occasional error messages as seen below. Accessories seem to function correctly but my log is flooded constantly with these messages.

### Expected behavior

Plugin should be able to check for updates and no more syntax errors

### Logs

[7/23/2024, 8:02:10 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:10 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:11 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:11 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:12 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:12 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:13 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:13 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:14 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:14 PM] [Tapo] Error sending command: getTriggerLogs Error: [KLAP] Request failed: SyntaxError: Bad control character in string literal in JSON at position 14
    at KlapAPI.sendSecureRequest (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:87:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TPLink.sendCommandWithNoLock (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/TPLink.ts:243:24)
[7/23/2024, 8:02:14 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:15 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:15 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:16 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:16 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:17 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:17 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:18 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:19 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:19 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:20 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:20 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:21 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:21 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:22 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:22 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:23 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:23 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:24 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:24 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:25 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:25 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:26 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:26 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:27 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:27 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:28 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:29 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:29 PM] [Tapo] Failed to check for updates, delaying 500ms
[7/23/2024, 8:02:30 PM] [Tapo] Error sending command: getTriggerLogs Error: [KLAP] Request failed: SyntaxError: Bad control character in string literal in JSON at position 15
    at KlapAPI.sendSecureRequest (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:87:13)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at TPLink.sendCommandWithNoLock (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/TPLink.ts:243:24)
[7/23/2024, 8:02:30 PM] [Tapo] Failed to check for updates, delaying 500ms

### Plugin Config

{
    "addresses": [
        "192.168.1.200"
    ],
    "name": "Tapo",
    "email": "******@******.com",
    "password": "***********",
    "_bridge": {
        "username": "MAC ADDRESS",
        "port": PORT
    },
    "platform": "HomebridgeTPLinkTapo"
}

### Plugin Version

4.1.1

### Homebridge Version

1.8.4

### Node.js Version

20.15.0

### NPM Version

10.8.2

### Operating System

Ubuntu Jammy (22.04.4 LTS)

**Comment by mogpt** [comment]
yesss, I have the same issue. everytime I need to check the logs for something else I have to disable this plugin lool
