### ISSUE TITLE
This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! 

### ISSUE THREAD

**Issue by jonathan-fielding** [RaresAil/homebridge-tplink-smart-light#39]
### Describe The Bug

When I turn on my lights sometimes it doesn't work and I think its because of this warning in the logs

```
[4/14/2023, 7:59:58 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
```

### Expected behavior

Lights should turn on correctly

### Logs

[4/14/2023, 7:59:58 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

### Plugin Config

{
    "addresses": [
        "192.168.4.25",
        "192.168.4.26",
        "192.168.6.28",
        "192.168.6.27",
        "192.168.6.26",
        "192.168.6.25",
        "192.168.6.43",
        "192.168.6.42",
        "192.168.6.39",
        "192.168.6.38"
    ],
    "name": "Tapo",
    "email": "",
    "password": "",
    "_bridge": {
        "username": "0E:59:4B:25:5A:84",
        "port": 43114
    },
    "platform": "HomebridgeTPLinkTapo"
}

### Plugin Version

3.2.2

### Homebridge Version

1.6.0

### Node.js Version

16.16.0

### NPM Version

no idea

### Operating System

Synology OS

**Comment by RaresAil** [comment]
Do you have any other logs?

**Comment by RaresAil** [comment]
From that error i can tell that the Light didn't responded

**Comment by jonathan-fielding** [comment]
Previously I only saw that however I just looked at logs again and saw this new error that seems to happen fairly often

```Error sending command: deviceInfo AxiosError: socket hang up
    at Function.AxiosError.from (/volume1/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/volume1/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/adapters/http.js:533:25)
    at RedirectableRequest.emit (node:events:527:28)
    at ClientRequest.eventHandlers.<computed> (/volume1/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at Socket.socketOnEnd (node:_http_client:478:9)
    at Socket.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: null },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      Cookie: 'TP_SESSIONID=DD900231F6E68C380073853F9508023B',
      'User-Agent': 'axios/1.2.2',
      'Content-Length': '226',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    method: 'post',
    url: 'http://192.168.6.43/app?token=XXXXXX',
    data: '{"method":"securePassthrough","params":{"request":"C+4S+eujcvt6H5gOv3JQbtuO3Tqieljofd3w+VyRMO9TqLAWTB++qpYFbQQPy9dZ+VkNtNaCMYUVQZAC5k4qsbgzgB5FAWtazfM7BiqXJViJh7fBJ/UnJ6A1KlUStZcxreW76Bku1wNGAsAm49dMQJB6q2OzgqbwOJ43a4485hE="}}'
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/app?token= XXXXXX',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '192.168.6.43',
      port: '',
      agent: undefined,
      nativeProtocols: [Object],
      pathname: '/app',
      search: '?token= XXXXXX'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 226,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /app?token= XXXXXX HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'Cookie: TP_SESSIONID=DD900231F6E68C380073853F9508023B\r\n' +
        'User-Agent: axios/1.2.2\r\n' +
        'Content-Length: 226\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Host: 192.168.6.43\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/app?token= XXXXXX',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.6.43',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    _currentUrl: 'http://192.168.6.43/app?token= XXXXXX',
    [Symbol(kCapture)]: false
  },
  cause: Error: socket hang up
      at connResetException (node:internal/errors:692:14)
      at Socket.socketOnEnd (node:_http_client:478:23)
      at Socket.emit (node:events:539:35)
      at endReadableNT (node:internal/streams/readable:1345:12)
      at processTicksAndRejections (node:internal/process/task_queues:83:21) {
    code: 'ECONNRESET'
  }
}```

**Comment by jonathan-fielding** [comment]
I think I censored anything potentially sensitive in the log, pls let me know if I missed something

**Comment by RaresAil** [comment]
@jonathan-fielding Looks like an issue with the device itself where is not responding back to the bridge, try reseting it, or check other closed issues here where this happend before

**Comment by Bram-Brooks** [comment]
I have the same issue with L630 bulbs. These are all newly installed and updated to the latest firmware. Any idea what could be wrong?
