### ISSUE TITLE
Bug with P100 1.2.1 Firware

### ISSUE THREAD

**Issue by AH-IT-SLTN** [RaresAil/homebridge-tplink-smart-light#57]
### Describe The Bug

Local Authentification is not working with Firmware 1.2.1 on P100

### Expected behavior

Working Auth

### Logs

Error sending command: deviceInfo TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:372:5)
    at Function.from (node:buffer:323:9)
    at LegacyAPI.decodeHandshakeKey (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:161:31)
    at LegacyAPI.handshake (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:153:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at LegacyAPI.sendSecureRequest (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:75:7)
    at LegacyAPI.login (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:19:22)
    at TPLink.sendCommandWithNoLock (/homebridge/node_modules/homebridge-tp-link-tapo/src/api/TPLink.ts:195:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### Plugin Config

{
    "bridge": {
        "name": "Homebridge TAPO2",
        "username": "02:32:54:88:99:22",
        "port": 59686,
        "pin": "034-25-154"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "TPLink Tapo Platform",
            "email": "++@++",
            "password": "+++",
            "platform": "HomebridgeTPLinkTapo",
            "addresses": ["10.123.0.76","10.123.0.71","10.123.0.78","10.123.0.79"]
        }
    ]
}

### Plugin Version

latest

### Homebridge Version

latest

### Node.js Version

latest

### NPM Version

latest

### Operating System

docker

**Comment by BenSmartHome** [comment]
Yep, i have the same issue atm with P100 and Firmware 1.2.1
No Problems directly in Tapo App. Controlable with Tapo App.

[12.9.2023, 20:43:04] [TapoPlug] Try for 192.168.0.192 : 1/20
[12.9.2023, 20:43:04] [TapoPlug] Error sending command: deviceInfo TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:333:9)
    at LegacyAPI.decodeHandshakeKey (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:161:31)
    at LegacyAPI.handshake (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:153:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LegacyAPI.sendSecureRequest (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:75:7)
    at LegacyAPI.login (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:19:22)
    at TPLink.sendCommandWithNoLock (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/TPLink.ts:195:9) {
  code: 'ERR_INVALID_ARG_TYPE'
 [12.9.2023, 20:43:04] [TapoPlug] Failed to get info about: 192.168.0.192  
  Config:
{
    "addresses": [
        "192.168.0.168",
        "192.168.0.192",
        "192.168.0.210"
    ],
    "name": "TapoPlug",
    "email": "xxxxxxxxxxxx@yyyyyy.zzz",
    "password": "xxxxxxxxxxxxxxxxxxxxxxxx",
    "platform": "HomebridgeTPLinkTapo",
    "_bridge": {
        "username": "xx:xx:xx:xx:xx:xx",
        "port": xxxxx
    }
}

**Comment by MarkWeber123** [comment]
I have the same Bug with my P100 since today. Installing an older version of the plugin doesn´t help.

**Comment by RaunoT** [comment]
Facing the same issue.

**Comment by RaresAil** [comment]
Hello, today i will release version 4.0.0 that adds support for KLAP, is a new protocol that Tapo started using it for his light, based on your error i think your P100 also uses that so that version might fix it

**Comment by BenSmartHome** [comment]
Thanks Rares! 
Will give you feedback after the update!

**Comment by RaresAil** [comment]
Hey, please try to update to v4.0.0

**Comment by MarkWeber123** [comment]
With version 4.0.0 my P100 are working again without any problems, thanks for your fast response and help!!!

**Comment by RaresAil** [comment]
Great 😄
