### ISSUE TITLE
Completely broken after update

### ISSUE THREAD

**Issue by energiumOn** [RaresAil/homebridge-tplink-smart-light#58]
### Describe The Bug

After I updated L510 and L530 to firmware version to 1.3.0, all links were broken on Homebridge. 
Tapo devices are no longer reachable on HomeKit anymore.

### Expected behavior

N/A

### Logs

[9/12/2023, 11:07:00 PM] [IoT] Failed to get info about: 10.144.1.46
[9/12/2023, 11:07:00 PM] [IoT] Retry to connect in 10s : 10.144.1.46
[9/12/2023, 11:07:00 PM] [IoT] Error sending command: deviceInfo TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:333:9)
    at LegacyAPI.decodeHandshakeKey (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:161:31)
    at LegacyAPI.handshake (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:153:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at LegacyAPI.sendSecureRequest (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:75:7)
    at LegacyAPI.login (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/LegacyAPI.ts:19:22)
    at TPLink.sendCommandWithNoLock (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/src/api/TPLink.ts:195:9) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### Plugin Config

N/A

### Plugin Version

v3.4.0

### Homebridge Version

v1.6.1

### Node.js Version

v18.17.1

### NPM Version

N/A

### Operating System

Debian

**Comment by pirates-killer** [comment]
Happened to me also with L510, same error message.

**Comment by RaresAil** [comment]
Hey, the fix for this is under development, there is another ticket for this issue, if you want real time updates you can join discord 😄

Dublicate of #49
