### ISSUE TITLE
TPLink Tapo sluggish, unresponsive and not working

### ISSUE THREAD

**Issue by axlwinter** [RaresAil/homebridge-tplink-smart-light#67]
### Describe The Bug

Hi,

I am experiencing a couple of issues which I do not know if they are related or not.

1. When I start the "Home" app all the Tapo bulbs and LEDs in my home says "Updating..." for about 20-25 seconds..
2. When "Updating..." is finally done a good number (about 25-75%) of the Tapo devices says "No response". This appears to be more or less random as a device may work one minute and the next time I load the Tapo app it will not work. All the devices work 100% in the official Tapo app so it is not a connectivity or network issue. All Tapo devices have static/reserved IP addresses in the router to make sure the IP addresses never change. 
3. I get very strange logs from the Tapo plugin in Homebridge and it uses quite a lot of CPU power as well.

### Expected behavior

It should work at not be 50/50 whether the lights will turn on or not in HomeKit.

### Logs

[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Hue' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Saturation' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Color Temperature' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Hue' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Saturation' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Color Temperature' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Hue' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Saturation' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Color Temperature' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Hue' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Saturation' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[10/23/2023, 3:09:51 AM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Color Temperature' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

### Plugin Config

{
    "bridge": {
        "name": "Homebridge 4348",
        "username": "XXX",
        "port": 51080,
        "pin": "XXX",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "options": {
                "email": "XXX,
                "password": "XXX"
            },
            "name": "Dreo Platform",
            "platform": "DreoPlatform",
            "_bridge": {
                "username": "XXX",
                "port": 32227
            }
        },
        {
            "addresses": [
                "192.168.1.11",
                "192.168.1.12",
                "192.168.1.15",
                "192.168.1.19",
                "192.168.1.20",
                "192.168.1.22",
                "192.168.1.24",
                "192.168.1.25",
                "192.168.1.26",
                "192.168.1.42",
                "192.168.1.43",
                "192.168.1.44"
            ],
            "name": "Homebridge TPLink Tapo",
            "email": "XXX,
            "password": "XXX",
            "platform": "HomebridgeTPLinkTapo",
            "_bridge": {
                "username": "XXX",
                "port": 59970
            }
        },
        {
            "name": "TplinkSmarthome ",
            "addCustomCharacteristics": true,
            "deviceTypes": [
                "plug",
                "bulb"
            ],
            "platform": "TplinkSmarthome",
            "_bridge": {
                "username": "XXX",
                "port": 55003
            }
        },
        {
            "name": "Levoit Air Purifiers",
            "email": "XXX,
            "password": "XXX",
            "experimentalFeatures": [
                "DeviceDisplay"
            ],
            "platform": "LevoitAirPurifiers",
            "_bridge": {
                "username": "XXX",
                "port": 59963
            }
        }
    ],
    "disabledPlugins": []
}

### Plugin Version

homebridge-tp-link-tapo v4.0.0

### Homebridge Version

1.6.1

### Node.js Version

18.18.2

### NPM Version

10.2.1

### Operating System

Ubuntu 22.04.3 LTS

**Comment by axlwinter** [comment]
Would appreciate any feedback and help on getting this resolved as it is now I cannot rely on HomeKit for Tapo devices. It is totally unreliable.

Thanks!

**Comment by RaresAil** [comment]
What devices do you have? Usually the high cpu should be if you have a Hub cause it has to check for updates

**Comment by axlwinter** [comment]
Hi

Thanks for your prompt reply. I am using the following devices:

L530 (bulbs)
L920 (LED strips)

Previously I had a H100 hub in addition but I removed it per your instructions. I don't really need it anyway. 

The problems persist. The Tapo units still say “Updating…” for 20 seconds or so when starting the HomeKit app. When it has finished “Updating…” about 25-50% of them have status “No Response” and I am still getting loads of errors in the Homebridge Logs similar to what I posted yesterday.

Any idea?

**Comment by axlwinter** [comment]
Now I got this message in the log as well:. The IP address it is referring to is a L530 build. 

[10/23/2023, 2:53:51 PM] [Homebridge TPLink Tapo] Error sending command: deviceInfo AxiosError: read ETIMEDOUT
    at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/adapters/http.js:593:25)
    at RedirectableRequest.emit (node:events:517:28)
    at ClientRequest.eventHandlers.<computed> (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  syscall: 'read',
  code: 'ETIMEDOUT',
  errno: -110,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: 'http',
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': 'application/octet-stream',
      Host: '192.168.1.43',
      Cookie: 'TP_SESSIONID=78A71F1AE758951F9897901AD7A81518',
      'User-Agent': 'axios/1.5.0',
      'Content-Length': '80',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    responseType: 'arraybuffer',
    params: { seq: '-1806665351' },
    httpAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    method: 'post',
    url: 'http://192.168.1.43/app/request',
    data: <Buffer 8e 92 f3 ee 02 ea f1 bf 4c 13 c0 34 ce 88 c9 ca a9 8e ba 32 83 80 cd da 0a a6 d4 6f de db cb a2 86 0e 5d bd 39 ee 66 01 28 54 fa b4 1f e5 f3 9b 84 4e ... 30 more bytes>
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/app/request?seq=-1806665351',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '192.168.1.43',
      port: '',
      agent: [Agent],
      nativeProtocols: [Object],
      pathname: '/app/request',
      search: '?seq=-1806665351'
    },
    _ended: true,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 80,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '80',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /app/request?seq=-1806665351 HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: application/octet-stream\r\n' +
        'Host: 192.168.1.43\r\n' +
        'Cookie: TP_SESSIONID=78A71F1AE758951F9897901AD7A81518\r\n' +
        'User-Agent: axios/1.5.0\r\n' +
        'Content-Length: 80\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/app/request?seq=-1806665351',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.1.43',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://192.168.1.43/app/request?seq=-1806665351',
    [Symbol(kCapture)]: false
  },
  cause: Error: read ETIMEDOUT
      at TCP.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -110,
    code: 'ETIMEDOUT',
    syscall: 'read'
  }
}

**Comment by 4ll4n** [comment]
Getting the same issue with a bunch of L630 spotlight bulbs

**Comment by RaresAil** [comment]
Do your routers have `IPMG V3` ? if yes, disabled it

**Comment by axlwinter** [comment]
I don't think my router has that? How can I tell?

**Comment by DrConflict** [comment]
I'm having the same issue with L630 light bulbs and HB. Anyone found a solution to this yet? The error log states:

'This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.'

**Comment by enrvuk** [comment]
I get a similar problem if my lightbulb is switched off at the wall. A restart of the homebridge solves it.

**Comment by axlwinter** [comment]
I've also found that restarting Homebridge helps. I currently have a crontab job restarting Homebridge every 8 hours and it seems to have mitigated a lot of the issues I was experiencing.
