### ISSUE TITLE
Homebridge Console getting littered with "this plugin slows down" message and light bulb is unresponsive in just homebridge

### ISSUE THREAD

**Issue by DPodDolphin** [RaresAil/homebridge-tplink-smart-light#87]
### Describe The Bug

[1/29/2024, 4:41:47 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:47 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

The console is getting littered with this error, and one specific device (a L510 light bulb) is unresponsive through homebridge. It is accessible perfectly normally through the Tapo app. This just started happening within the last 48 hours, I haven't touched homebridge at all until now to troubleshoot.

### Expected behavior

The light to be able to turn on and off

### Logs

[1/29/2024, 4:34:17 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:17 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:23 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:23 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:40 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:40 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:59 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:34:59 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:35:05 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:35:05 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:35:37 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:35:37 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:35:43 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:35:43 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:09 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:09 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:15 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:15 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:22 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:22 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:28 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:28 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:44 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:44 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:50 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:36:50 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:07 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:07 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:13 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:13 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:51 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:51 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:57 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:37:57 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:01 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:01 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:14 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:14 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:20 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:20 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:36 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:38:36 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:02 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:02 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:08 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:08 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:24 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:24 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:30 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:30 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:46 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:39:46 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:05 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:05 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:11 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:11 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:27 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:27 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:33 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:40:33 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:09 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:09 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:15 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:15 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:41 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:41 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:47 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:41:47 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:16 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:16 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:22 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:22 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:50 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:50 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' was slow to respond! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:56 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'On' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.
[1/29/2024, 4:42:56 PM] [homebridge-tp-link-tapo] This plugin slows down Homebridge. The read handler for the characteristic 'Brightness' didn't respond at all!. Please check that you properly call the callback! See https://homebridge.io/w/JtMGR for more info.

### Plugin Config

{
            "addresses": [
                "192.168.0.21",
                "192.168.0.22",
                "192.168.0.20"
            ],
            "name": "TPLink Tapo Platform",
            "email": "redacted",
            "password": "redacted",
            "platform": "HomebridgeTPLinkTapo"
        },

### Plugin Version

v4.1.0

### Homebridge Version

v1.6.1

### Node.js Version

v18.16.0

### NPM Version

Unknown

### Operating System

Raspberry Pi OS

**Comment by DPodDolphin** [comment]
More Logs which seem more helpful to my untrained eye

rror sending command: deviceInfo AxiosError: connect EHOSTUNREACH 192.168.0.20:80
    at Function.AxiosError.from (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/core/AxiosError.js:89:14)
    at RedirectableRequest.handleRequestError (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/adapters/http.js:606:25)
    at RedirectableRequest.emit (node:events:517:28)
    at ClientRequest.eventHandlers.<computed> (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:517:28)
    at Socket.socketErrorListener (node:_http_client:501:9)
    at Socket.emit (node:events:517:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  port: 80,
  address: '192.168.0.20',
  syscall: 'connect',
  code: 'EHOSTUNREACH',
  errno: -113,
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: Object [AxiosHeaders] {
      Accept: '*/*',
      'Content-Type': 'application/octet-stream',
      Host: '192.168.0.20',
      Cookie: 'TP_SESSIONID=C30B8D1383318E04B9110905998C8806',
      'User-Agent': 'axios/1.6.2',
      'Content-Length': '80',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    responseType: 'arraybuffer',
    params: { seq: '-169366123' },
    httpAgent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    method: 'post',
    url: 'http://192.168.0.20/app/request',
    data: <Buffer a1 f7 10 14 52 5b 3c fa 74 2e 04 19 b7 35 7d bb 4a fd aa 24 d5 82 64 ba ca 74 9f 70 4e ad e2 d6 b0 60 e0 60 6a 5f 64 f6 a9 7d 44 29 96 60 b6 7b 46 ff ... 30 more bytes>
  },
  request: <ref *1> Writable {
    _writableState: WritableState {
      objectMode: false,
      highWaterMark: 16384,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: false,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: true,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 0,
      constructed: true,
      prefinished: false,
      errorEmitted: false,
      emitClose: true,
      autoDestroy: true,
      errored: null,
      closed: false,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    _events: [Object: null prototype] {
      response: [Function: handleResponse],
      error: [Function: handleRequestError],
      socket: [Function: handleRequestSocket]
    },
    _eventsCount: 3,
    _maxListeners: undefined,
    _options: {
      maxRedirects: 21,
      maxBodyLength: Infinity,
      protocol: 'http:',
      path: '/app/request?seq=-169366123',
      method: 'POST',
      headers: [Object: null prototype],
      agents: [Object],
      auth: undefined,
      family: undefined,
      beforeRedirect: [Function: dispatchBeforeRedirect],
      beforeRedirects: [Object],
      hostname: '192.168.0.20',
      port: '',
      agent: [Agent],
      nativeProtocols: [Object],
      pathname: '/app/request',
      search: '?seq=-169366123'
    },
    _ended: false,
    _ending: true,
    _redirectCount: 0,
    _redirects: [],
    _requestBodyLength: 80,
    _requestBodyBuffers: [ [Object] ],
    _onNativeResponse: [Function (anonymous)],
    _currentRequest: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '80',
      _hasBody: true,
      _trailer: '',
      finished: false,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST /app/request?seq=-169366123 HTTP/1.1\r\n' +
        'Accept: */*\r\n' +
        'Content-Type: application/octet-stream\r\n' +
        'Host: 192.168.0.20\r\n' +
        'Cookie: TP_SESSIONID=[this looks sensitive so I redacted it]\r\n' +
        'User-Agent: axios/1.6.2\r\n' +
        'Content-Length: 80\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: '/app/request?seq=-169366123',
      _ended: false,
      res: null,
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.0.20',
      protocol: 'http:',
      _redirectable: [Circular *1],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kHighWaterMark)]: 16384,
      [Symbol(kRejectNonStandardBodyWrites)]: false,
      [Symbol(kUniqueHeaders)]: null
    },
    _currentUrl: 'http://192.168.0.20/app/request?seq=-169366123',
    [Symbol(kCapture)]: false
  },
  cause: Error: connect EHOSTUNREACH 192.168.0.20:80
      at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16) {
    errno: -113,
    code: 'EHOSTUNREACH',
    syscall: 'connect',
    address: '192.168.0.20',
    port: 80
  }
}

**Comment by DPodDolphin** [comment]
My sockets (P100) are now throwing the same error. Nothing works.

**Comment by DPodDolphin** [comment]
The sockets are now not throwing the error... weird

**Comment by benammiswift** [comment]
I had this too. not sure how to fix but I now run my sockets through a different module
