### ISSUE TITLE
Error sending command: deviceInfo AxiosError: Request failed with status code 403

### ISSUE THREAD

**Issue by cydalby** [RaresAil/homebridge-tplink-smart-light#96]
### Describe The Bug

Light works on first setup, but after a minute or so starts responding with 403s for both `deviceInfo` and `power`

### Expected behavior

Response code 200

### Logs

[09/05/2024, 21:38:41] [TPLink Tapo Platform] Error sending command: deviceInfo AxiosError: Request failed with status code 403
    at settle (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (/var/lib/homebridge/node_modules/homebridge-tp-link-tapo/node_modules/axios/lib/adapters/http.js:585:11)

### Plugin Config

`{
            "addresses": [
                "192.168.0.132"
            ],
            "name": "TPLink Tapo Platform",
            "email": ****,
            "password": ****,
            "platform": "HomebridgeTPLinkTapo"
        }`

### Plugin Version

4.1.0

### Homebridge Version

1.8.1

### Node.js Version

20.12.0

### NPM Version

10.5.0

### Operating System

Linux Buster

**Comment by dmazin** [comment]
Yep, happening for me too.

**Comment by bicornenoir** [comment]
That affects me too.
