### ISSUE TITLE
P100 Failed to verify server hash

### ISSUE THREAD

**Issue by roricoco** [RaresAil/homebridge-tplink-smart-light#98]
### Describe The Bug

I connected using the P100 product and the corresponding plug-in, but 2 out of 3 are not connected.

deviceInfo Error: Failed to verify server hash
    at KlapAPI.firstHandshake (/volume2/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:196:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /volume2/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:109:51

### Expected behavior

Must be properly connected to homebridge

### Logs

[6/1/2024, 9:50:36 PM] [TPLink Tapo] Error sending command: deviceInfo Error: Failed to verify server hash
    at KlapAPI.firstHandshake (/volume2/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:196:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /volume2/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:109:51
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Failed to get info about: 192.168.1.150
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Retry to connect in 10s : 192.168.1.150
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Error sending command: deviceInfo Error: Failed to verify server hash
    at KlapAPI.firstHandshake (/volume2/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:196:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at /volume2/homebridge/node_modules/homebridge-tp-link-tapo/src/api/KlapAPI.ts:109:51
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Failed to get info about: 192.168.1.85
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Retry to connect in 10s : 192.168.1.85
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Adding new accessory: 휴대등충전기
[휴대등충전기@@Contact Sensor State] Characteristic not in required or optional characteristic section for service Outlet. Adding anyway.
[6/1/2024, 9:50:36 PM] [TPLink Tapo] Command error: getCurrentPower > -1002

### Plugin Config

{
    "addresses": [
        "192.168.1.85",
        "192.168.1.145",
        "192.168.1.150"
    ],
    "name": "TPLink Tapo",
    "email": "-",
    "password": "-",
    "platform": "HomebridgeTPLinkTapo"
}

### Plugin Version

4.1.0

### Homebridge Version

3.1.1 (homebridge: 1.8.2, homebridge ui: 4.56.2)

### Node.js Version

20.9.0

### NPM Version

10.2.3

### Operating System

Synology DSM

**Comment by marsdeat** [comment]
I am having the same issue on a Raspberry Pi under Docker: one P100 out of my five devices (3 P100s and 2 bulbs) is connecting, the other four are giving the same error as in the original.

This also confirms behaviour I’ve been experiencing in Home Assistant: the exact same P100 is working while the others are not.

**Comment by mharmuth** [comment]
Same Problem here with the P110. Two devices are working and the other two not.

**Comment by nzscoff** [comment]
Same issue here. Tried resetting Tapo password, resetting and re-adding devices, etc, to no avail.

**Comment by nzscoff** [comment]
Same issue here. Tried resetting Tapo password, resetting and re-adding devices to no avail. I was previously running HomeBridge on it's own Raspberry Pi and it was working fine. I moved HomeBridge into Docker so I could run both HomeBridge and HomeAssistant on the same Pi and it hasn't worked since then. Seems to be something related to communicating out of the Docker environment?

**Comment by mharmuth** [comment]
@nzscoff I am running HomeBridge on a Rasperry Pi without Docker. So I don't think that this is the problem.

**Comment by glxgxr** [comment]
I can confirm this issue. I am trying to run it on a Rasperry Pi with Ubuntu 24.04 inside Docker.

**Comment by nickgro9898** [comment]
Exact same issue running homebridge on Raspberry Pi. Please help us.

**Comment by anastako** [comment]
+1 here 

both for P100 and the Light Strip L900
